[User]
call=N0CALL
password=secret

#operators=OP1X OP2Y

#---------------------
# common settings
# can be overrriden in a contest-specific section
# values are not case-sensitive
#
[Contest]
# simple single-op category specification
category=so80-qrp
mode=cw

# for more fine-grained control, details can also be specified
# (allowed values are listed, select one of them)
#power= LOW, HIGH, QRP
#transmitter= UNLIMITED, TWO, ONE
#ops= MULTI-OP, SINGLE-OP 
#bands= ALL, 160M, 80M, 40M, 20M, 15M, 10M
#assisted= YES, NO
#mode= MIXED, CW, PH, RTTY, PSK, FT8, FT4, DIGI
#overlay= N/A, TB-WIRES, ROOKIE, CLASSIC, WIRE-ONLY

# what mode to use for TLF's DIG
#digimode=rtty

#---------------------
# optional contest-specific settings
# also defining an alias (ttc) for contest name
#
[Contest-ttc]
# name must be either full contest name or Cabrillo name
# (not case-sensitive)
name=ttc-spcwc
logfile=~/ttc.log
category=soab-lp

