name: Makefile CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@main

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bats bats-assert

      - name: Build binary
        run: make

      - name: Run tests
        run: make test

#    - name: Run distcheck
#      run: make distcheck
